### ISSUE TITLE
missing `self.numlines` class attribute in Adafruit_CharLCD object

### ISSUE THREAD

**Issue by israel-dryer** [Freenove/Freenove_Super_Starter_Kit_for_Raspberry_Pi#1]
This is in reference to the file: `Adafruit_LCD1602.py`.  The `begin` method is referring to the `self.numlines` class attribute which does not exist.

![image](https://user-images.githubusercontent.com/42584742/64746440-8c660a00-d4d9-11e9-9f12-9134ce236752.png)

when changing the number of rows, I get the following error message:  

![image](https://user-images.githubusercontent.com/42584742/64746469-a56ebb00-d4d9-11e9-81d4-cc73a1e7f1f8.png)

**Comment by SuhaylZhao** [comment]
Hi ,

We checked and tested the code, and it worked properly.

Have you changed the code? If so, please carefully check and compare the differences between your code and ours. If you need our help to check your code, please send it to the mailbox support@freenove.com.

Thanks.

**Comment by israel-dryer** [comment]
The `begin` method does not handle a line value < 2. If you pass in 1 for lines, for example, `self.display` is never set and the program will crash when it tries to find that attribute in the `setCursor` method.

`self.numlines` should be set before the if statement to avoid this. However, if having 1 line is an option, that should be handled in the if/else block. Or, consider just adding default values if this method doesn't actually allow you to control the number of columns and lines used on the LCD.

```python
def begin(self, cols, lines):
    self.numlines = lines
    if(lines > 1):
        self.displayfunction |= self.LCD_2LINE
    else:
        self.displayfunction |= self.LCD_1LINE
```
